[General]
; Disable automatic unzoom when manually zooming in/out
bDisableUnzoomOnManualZoom=1
; Show a tooltip when toggling unzoom, switching between soft/fast unzoom and toggling unzoom off by manually zooming in (only works in windowed mode)
bShowTooltip=0
; Beep when toggling unzoom and switching between soft/fast unzoom
bSoundBeep=1
; Whether to use soft unzoom (holding down the zoom out key) or fast unzoom (spamming mouse wheel down)
bUseSoftUnzoom=0
; Number of times to send mouse wheel down at each timer interval in fast unzoom mode
iSpamCount=10
; How often should we send mouse wheel down in fast unzoom mode (in milliseconds)
iTimerInterval=100
; How long tooltips should be displayed (in milliseconds)
iTooltipDuration=1500

; See https://www.autohotkey.com/docs/v2/KeyList.htm for key IDs
[Keys]
; The keyboard key used to open the journal
sJournalKey="j"
; The keyboard key used to open the map
sMapKey="Tab"
; The keyboard key used to open the menu
sMenuKey="Escape"
; The keyboard key used to open the options
sOptionsKey="F10"
; The mouse button used to unzoom
sUnzoomButton="WheelDown"
; The keyboard key used to unzoom
sUnzoomKey="-"
; The key used to switch between soft and fast unzoom modes
sUnzoomSwitchKey="XButton2"
; The key used to toggle unzoom on and off
sUnzoomToggleKey="XButton1"
; The mouse button used to zoom
sZoomButton="WheelUp"
; The keyboard key used to zoom
sZoomKey="="
